### ISSUE TITLE
panic: Unable to hydrate the AWS launch template cache, UnauthorizedOperation: You are not authorized to perform this operation.

### ISSUE THREAD

**Issue by Skarlso** [aws/karpenter#1377]
## Version

**Karpenter**: v0.6.2

**Kubernetes**: v1.21.0

## Expected Behavior

Everything to work.

## Actual Behavior

When installing Karpenter I get that error message from the controller.

## Steps to Reproduce the Problem

Install Karpenter.

## Resource Specs and Logs

```
2022-02-18T07:29:24.259Z        INFO    Successfully created the logger.
2022-02-18T07:29:24.259Z        INFO    Logging level set to: info
{"level":"info","ts":1645169364.3655457,"logger":"fallback","caller":"injection/injection.go:61","msg":"Starting informers..."}
panic: Unable to hydrate the AWS launch template cache, UnauthorizedOperation: You are not authorized to perform this operation.
        status code: 403, request id: d2a2f015-7d8f-4d84-9400-c74f8631054c

goroutine 1 [running]:
github.com/aws/karpenter/pkg/cloudprovider/aws.(*LaunchTemplateProvider).hydrateCache(0xc00012afc0, {0x27c0938, 0xc0007dd7a0})
        github.com/aws/karpenter/pkg/cloudprovider/aws/launchtemplate.go:234 +0x4f4
github.com/aws/karpenter/pkg/cloudprovider/aws.NewLaunchTemplateProvider({0x27c0938, 0xc0007dd7a0}, {0x28952a0, 0xc000330368}, 0xc00008b7e0, 0xc0000eba28)
        github.com/aws/karpenter/pkg/cloudprovider/aws/launchtemplate.go:68 +0x1d1
github.com/aws/karpenter/pkg/cloudprovider/aws.NewCloudProvider({0x27c0938, 0xc0007dd770}, {0x1faaee0})
        github.com/aws/karpenter/pkg/cloudprovider/aws/cloudprovider.go:88 +0x4fb
github.com/aws/karpenter/pkg/cloudprovider/registry.newCloudProvider(...)
        github.com/aws/karpenter/pkg/cloudprovider/registry/aws.go:27
github.com/aws/karpenter/pkg/cloudprovider/registry.NewCloudProvider({0x27c0938, 0xc0007dd770}, {0x1faaee0})
        github.com/aws/karpenter/pkg/cloudprovider/registry/register.go:25 +0x28
main.main()
        github.com/aws/karpenter/cmd/controller/main.go:76 +0x257
```

The following permissions are attached to the role:

```go
		"Action": []string{
			ec2CreateFleet,
			ec2CreateLaunchTemplate,
			ec2CreateTags,
			ec2DescribeAvailabilityZones,
			ec2DescribeInstanceTypeOfferings,
			ec2DescribeInstanceTypes,
			ec2DescribeInstances,
			ec2DescribeLaunchTemplates,
			ec2DescribeSecurityGroups,
			ec2DescribeSubnets,
			ec2DeleteLaunchTemplate,
			ec2RunInstances,
			ec2TerminateInstances,
			iamPassRole,
			ssmGetParameter,
		},
```

**Comment by Skarlso** [comment]
I think this behaviour now requires `ec2:ModifyLaunchTemplate` as well?

**Comment by Skarlso** [comment]
Never mind. The problem was that the service account didn't get the right role name I think. When I let Karpenter create the service account it works. So I'm probably messing up something. :)

**Comment by Skarlso** [comment]
Nope, I made sure that the right role and account are used and this is still an issue in case we pass in the role and create the service account ourself.

**Comment by Skarlso** [comment]
Service account created by us:

```
k describe serviceaccount -n karpenter karpenter
Name:                karpenter
Namespace:           karpenter
Labels:              app.kubernetes.io/managed-by=eksctl
Annotations:         eks.amazonaws.com/role-arn: arn:aws:iam::<account-id>:role/eksctl-cluster-with-karpenter-9-iamservice-role
Image pull secrets:  <none>
Mountable secrets:   karpenter-token-dhd2d
Tokens:              karpenter-token-dhd2d
Events:              <none>
```

**Comment by Skarlso** [comment]
Again.... never mind. 🤦
