### ISSUE TITLE
v0.14.0-rc.0 Karpenter pods crashed with high resource limit/request

### ISSUE THREAD

**Issue by kai-cash** [aws/karpenter#2266]
## Version

**Karpenter**: v0.14.0-rc.0

**Kubernetes**: v1.21.13

## Expected Behavior
Karpenter pods running successfully

## Actual Behavior
Karpenter pods crashloopbackoff

## Steps to Reproduce the Problem

1. Deploy Karpenter with high resource limit/request
2. Observe Karpenter pods crashed

## Resource Specs and Logs

Our resource config:
```
resources = {
        requests = {
          cpu    = "2"
          memory = "2Gi"
        }
        limits   = {
          cpu    = "3"
          memory = "3Gi"
        }
      }
```

Karpenter node group instance type:
```
instance_types:
    - m5.2xlarge
```

crashed pod controller log shows:
```
fatal error: concurrent map writes

goroutine 645 [running]:
runtime.throw({0x23de149?, 0xc028361508?})
	runtime/panic.go:992 +0x71 fp=0xc021da58e8 sp=0xc021da58b8 pc=0x4385d1
runtime.mapassign(0x1fbf320?, 0xc021dae270?, 0xc021dae030?)
	runtime/map.go:595 +0x4d6 fp=0xc021da5968 sp=0xc021da58e8 pc=0x40f476
github.com/aws/karpenter/pkg/controllers/state.(*Cluster).populateResourceRequests(0xc0007c1380, {0x2850e28, 0xc021dae030}, 0xc021daac00, 0xc007b020e0)
	github.com/aws/karpenter/pkg/controllers/state/cluster.go:253 +0x57d fp=0xc021da5be8 sp=0xc021da5968 pc=0x1c754bd
github.com/aws/karpenter/pkg/controllers/state.(*Cluster).newNode(0xc0007c1380, {0x2850e28, 0xc021dae030}, 0xc021daac00)
	github.com/aws/karpenter/pkg/controllers/state/cluster.go:184 +0x2ed fp=0xc021da5c78 sp=0xc021da5be8 pc=0x1c7438d
github.com/aws/karpenter/pkg/controllers/state.(*Cluster).updateNode(0xc0007c1380, {0x2850e28?, 0xc021dae030?}, 0xc021daac00)
	github.com/aws/karpenter/pkg/controllers/state/cluster.go:296 +0x54 fp=0xc021da5cf8 sp=0xc021da5c78 pc=0x1c761b4
github.com/aws/karpenter/pkg/controllers/state.(*NodeController).Reconcile(0xc00000d578, {0x2850e28, 0xc021bddfb0}, {{{0x0?, 0x21e49c0?}, {0xc0209d9a10?, 0xc011d84240?}}})
	github.com/aws/karpenter/pkg/controllers/state/node.go:57 +0x265 fp=0xc021da5dc0 sp=0xc021da5cf8 pc=0x1c78b65
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000df7400, {0x2850d80, 0xc00013b7c0}, {0x20e7d20?, 0xc021ba6ec0?})
	sigs.k8s.io/controller-runtime@v0.9.7/pkg/internal/controller/controller.go:298 +0x2f9 fp=0xc021da5ee0 sp=0xc021da5dc0 pc=0x1599e59
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000df7400, {0x2850d80, 0xc00013b7c0})
	sigs.k8s.io/controller-runtime@v0.9.7/pkg/internal/controller/controller.go:253 +0x1d9 fp=0xc021da5f80 sp=0xc021da5ee0 pc=0x15996d9
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
	sigs.k8s.io/controller-runtime@v0.9.7/pkg/internal/controller/controller.go:214 +0x85 fp=0xc021da5fe0 sp=0xc021da5f80 pc=0x1599145
runtime.goexit()
	runtime/asm_amd64.s:1571 +0x1 fp=0xc021da5fe8 sp=0xc021da5fe0 pc=0x46b201
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
	sigs.k8s.io/controller-runtime@v0.9.7/pkg/internal/controller/controller.go:210 +0x307
```

possible related PR:
https://github.com/aws/karpenter/commit/d7e79d6de79b6c04c168a5ea2f23ccd0945cea7b#diff-0c263e0dd69b177721a8174c7dd6e5dc2f89574843afdc095d6d5a26642e3085
this moved the newNode call out of lock, which may cause concurrent write to https://github.com/aws/karpenter/blob/ba600d8038747224dd55d89156e4bd65512a6000/pkg/controllers/state/cluster.go#L254

**Comment by tzneal** [comment]
Yup, good catch.  I thought I looked at it closely, apparently not 🤦
