### ISSUE TITLE
Helm upgrade to 0.28.0 fails in EKS 

### ISSUE THREAD

**Issue by Constantin07** [aws/karpenter#4057]
### Version

__Karpenter Version:__ v0.28.0

__Kubernetes Version:__ v1.25.9

### Expected Behavior

Helm upgrade from 0.27.6 to 0.28.0 to go successfully.

### Actual Behavior

Pod is crashing in the loop continuously.

### Steps to Reproduce the Problem

1. Have the 0.27.6 of Karpenter deployed to EKS cluster.
2. Run helm upgrade:
```sh
$ helm upgrade --install -n kube-system karpenter oci://public.ecr.aws/karpenter/karpenter --version v0.28.0 -f dev-values.yaml --wait --timeout=180s
```

3. Check the logs:
```sh
$ kubectl -n kube-system logs -l app.kubernetes.io/name=karpenter

goroutine 1 [running]:
github.com/samber/lo.must({0x2468720, 0xc00133ad00}, {0xc001241b08, 0x1, 0x1})
	github.com/samber/lo@v1.38.1/errors.go:51 +0x1cd
github.com/samber/lo.Must0(...)
	github.com/samber/lo@v1.38.1/errors.go:72
github.com/aws/karpenter-core/pkg/operator.NewOperator()
	github.com/aws/karpenter-core@v0.28.0/pkg/operator/operator.go:135 +0xc05
main.main()
	github.com/aws/karpenter/cmd/controller/main.go:33 +0x2e

goroutine 1 [running]:
github.com/samber/lo.must({0x2468720, 0xc001174600}, {0xc00103bb08, 0x1, 0x1})
	github.com/samber/lo@v1.38.1/errors.go:51 +0x1cd
github.com/samber/lo.Must0(...)
	github.com/samber/lo@v1.38.1/errors.go:72
github.com/aws/karpenter-core/pkg/operator.NewOperator()
	github.com/aws/karpenter-core@v0.28.0/pkg/operator/operator.go:135 +0xc05
main.main()
	github.com/aws/karpenter/cmd/controller/main.go:33 +0x2e
2023-06-15T08:12:26.691Z	ERROR	webhook.ValidationWebhook	Reconcile error	{"commit": "5a2fe84-dirty", "knative.dev/traceid": "339dda27-a697-4e9d-b707-58c0dc8034a7", "knative.dev/key": "validation.webhook.karpenter.k8s.aws", "duration": "48.522µs", "error": "secret \"karpenter-cert\" is missing \"ca-cert.pem\" key"}
2023-06-15T08:12:26.692Z	ERROR	webhook.WebhookCertificates	Reconcile error	{"commit": "5a2fe84-dirty", "knative.dev/traceid": "0a2d3586-a845-4795-ada9-2f8a4bec45fd", "knative.dev/key": "kube-system/karpenter-cert", "duration": "37.517212ms", "error": "Operation cannot be fulfilled on secrets \"karpenter-cert\": the object has been modified; please apply your changes to the latest version and try again"}
2023-06-15T08:12:27.011Z	ERROR	webhook.DefaultingWebhook	Reconcile error	{"commit": "5a2fe84-dirty", "knative.dev/traceid": "f2e2518b-29c8-4acb-8226-b2a4e7892025", "knative.dev/key": "kube-system/karpenter-cert", "duration": "318.120027ms", "error": "failed to update webhook: Operation cannot be fulfilled on mutatingwebhookconfigurations.admissionregistration.k8s.io \"defaulting.webhook.karpenter.k8s.aws\": the object has been modified; please apply your changes to the latest version and try again"}
2023-06-15T08:12:27.187Z	ERROR	webhook.ConfigMapWebhook	Reconcile error	{"commit": "5a2fe84-dirty", "knative.dev/traceid": "84c59f6e-a983-4fc1-8796-5f0cfe30a18a", "knative.dev/key": "kube-system/karpenter-cert", "duration": "494.41271ms", "error": "failed to update webhook: Operation cannot be fulfilled on validatingwebhookconfigurations.admissionregistration.k8s.io \"validation.webhook.config.karpenter.sh\": the object has been modified; please apply your changes to the latest version and try again"}
2023-06-15T08:12:27.504Z	ERROR	webhook.ValidationWebhook	Reconcile error	{"commit": "5a2fe84-dirty", "knative.dev/traceid": "8714f154-594e-4d74-b9c0-a45e490e464d", "knative.dev/key": "kube-system/karpenter-cert", "duration": "497.152141ms", "error": "failed to update webhook: Operation cannot be fulfilled on validatingwebhookconfigurations.admissionregistration.k8s.io \"validation.webhook.karpenter.sh\": the object has been modified; please apply your changes to the latest version and try again"}
2023-06-15T08:12:29.312Z	DEBUG	controller.provisioner	ignoring pod, configured to not run on a Karpenter provisioned node via karpenter.sh/provisioner-name DoesNotExist requirement	{"commit": "5a2fe84-dirty", "pod": "kube-system/karpenter-65cc9d6c68-lvh8w"}
2023-06-15T08:12:30.588Z	DEBUG	controller.deprovisioning	ignoring pod, configured to not run on a Karpenter provisioned node via karpenter.sh/provisioner-name DoesNotExist requirement	{"commit": "5a2fe84-dirty", "pod": "kube-system/karpenter-65cc9d6c68-lvh8w"}
2023-06-15T08:12:30.688Z	DEBUG	controller.deprovisioning	ignoring pod, configured to not run on a Karpenter provisioned node via karpenter.sh/provisioner-name DoesNotExist requirement	{"commit": "5a2fe84-dirty", "pod": "kube-system/karpenter-65cc9d6c68-lvh8w"}
2023-06-15T08:12:30.706Z	DEBUG	controller.deprovisioning	ignoring pod, configured to not run on a Karpenter provisioned node via karpenter.sh/provisioner-name DoesNotExist requirement	{"commit": "5a2fe84-dirty", "pod": "kube-system/karpenter-65cc9d6c68-lvh8w"}
2023-06-15T08:24:26.661Z	DEBUG	controller.provisioner	ignoring pod, configured to not run on a Karpenter provisioned node via karpenter.sh/provisioner-name DoesNotExist requirement	{"commit": "5a2fe84-dirty", "pod": "kube-system/karpenter-58fd6c7d87-tgxbq"}
```

### Resource Specs and Logs

```yaml
# Default provisioner
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  # References cloud provider-specific AWSNodeTemplate custom resource
  providerRef:
    name: default

  # Labels applied to all nodes provisioned by Karpenter
  labels:
    provisioner: karpenter

  requirements:
    - key: "karpenter.k8s.aws/instance-family"
      operator: In
      values: ["m5a", "m6a", "m6i", "m5"] # General purpose
    - key: "karpenter.k8s.aws/instance-cpu"
      operator: Lt
      values:
        - "33"
    - key: "karpenter.k8s.aws/instance-hypervisor"
      operator: In
      values: ["nitro"]
    - key: "topology.kubernetes.io/zone"
      operator: In
      values: ["eu-west-1a", "eu-west-1b", "eu-west-1c"]
    - key: "kubernetes.io/arch"
      operator: In
      values: ["amd64"]
    # Karpenter prioritizes Spot offerings.
    # If there are no other possible offerings available for Spot, Karpenter will attempt to provision on-demand instances
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["spot", "on-demand"]

  # Specify additional Kubelet args.
  kubeletConfiguration:
    containerRuntime: containerd
    # Reserve resources for system & kubelet
    systemReserved:
      cpu: 100m
      memory: 100Mi
      ephemeral-storage: 1Gi
    kubeReserved:
      cpu: 200m
      memory: 100Mi
      ephemeral-storage: 1Gi
    imageGCHighThresholdPercent: 85
    imageGCLowThresholdPercent: 80

  # Resource limits constrain the total size of the cluster.
  limits:
    resources:
      cpu: 32
      memory: 100Gi

  # Enables consolidation which attempts to reduce cluster cost by both removing un-needed nodes and down-sizing those
  # that can't be removed. Mutually exclusive with the ttlSecondsAfterEmpty parameter!
  consolidation:
    enabled: true

  # Terminate nodes that are not utilized.
  # ttlSecondsAfterEmpty: 30

---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: default
spec:
  # required, discovers tagged subnets to attach to instances
  subnetSelector:
    karpenter.sh/discovery: private
  # required, discovers tagged security groups to attach to instances
  securityGroupSelector:
    kubernetes.io/cluster/dev-eks-cluster: owned
    Name: dev-eks-cluster-node
  amiFamily: Bottlerocket
  amiSelector:
    # AMI in eu-west-1 region bottlerocket-aws-k8s-1.25-x86_64-v1.14.1-842c7134
    aws-ids: "ami-05c76528e624ccf03"
  tags:
    karpenter.sh/discovery: dev-eks-cluster
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 2
    httpTokens: required
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 2Gi
        volumeType: gp3
        encrypted: true
        kmsKeyID: "arn:aws:kms:eu-west-1:*****:key/****"
        deleteOnTermination: true
    - deviceName: /dev/xvdb
      ebs:
        volumeSize: 20Gi
        volumeType: gp3
        encrypted: true
        kmsKeyID: "arn:aws:kms:eu-west-1:*****:key/****"
        deleteOnTermination: true
  detailedMonitoring: true
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by njtran** [comment]
It looks like you're installing karpenter into the kube-system namespace. It should be installed into the karpenter namespace, as that has proper service account roles and such in there. Have you been running Karpenter in the kube-system system for v0.27.6?

**Comment by njtran** [comment]
Ah that makes sense. Had you updated the CRDs? v0.28.0 includes a new CRD. 

https://karpenter.sh/docs/upgrade-guide/#:~:text=v0.28.0%20introduces%20the,label%20on%20nodes.

**Comment by itek09** [comment]
The documentation to install is not up to date.

Missing the new CRD here https://karpenter.sh/docs/getting-started/migrating-from-cas/

**Comment by njtran** [comment]
@itek09, thanks for pointing that out! Updated it.
