### ISSUE TITLE
AssumeRole operation failing | AccessDenied

### ISSUE THREAD

**Issue by ashishkurian** [aws/karpenter#4680]
### Description

**Observed Behavior**:

The `Karpenter*` [Assumed-role session principal](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_principal.html#sts-session-principals) is denied to assume my cluster master role `EksAdminRole-mycluster`

`[ERROR] Exception: b'\nAn error occurred (AccessDenied) when calling the AssumeRole operation: User: arn:aws:sts::629146268066:assumed-role/Karpenter-KarpenterEksClu-HandlerServiceRoleFCDC14-1E2S2B6XVZBLW/Karpenter-KarpenterEksCluster73357-Handler886CB40B-1FCztK9eeCEe is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::629146268066:role/EksAdminRole-mycluster\nUnable to connect to the server: getting credentials: exec: executable aws failed with exit code 255\n'
Traceback (most recent call last):
  File "/var/task/index.py", line 14, in handler
    return apply_handler(event, context)
  File "/var/task/apply/__init__.py", line 64, in apply_handler
    kubectl('create', manifest_file, *kubectl_opts)
  File "/var/task/apply/__init__.py", line 91, in kubectl
    raise Exception(output)`

Thus the helm chart creation fails with the above error. 

As the sts assumed role principal name is dynamically generated, I cannot update my cluster master role to allow sts assume for the dynamic role.

**My Setup**:

AWS Python CDK.

```
from aws_cdk import (
  Stack,
  aws_eks as eks,
  aws_iam as iam,
  CfnJson as CfnJson,
  Fn as Fn,
  aws_sqs as sqs,
  aws_events as events,
  aws_events_targets as targets,
  Duration as duration,
  Tags
)

from constructs import Construct

class Karpenter(Stack):
  def __init__(self, scope: Construct, construct_id: str, **kwargs) -> None:
    super().__init__(scope, construct_id, **kwargs)

    cluster_props = self.node.try_get_context('eks_cluster')
    cluster_name = cluster_props['name']

    oidc_id = Fn.import_value(f"OIDC-ID-{cluster_name}")
    provider = eks.OpenIdConnectProvider.from_open_id_connect_provider_arn(self, "Provider", f"arn:aws:iam::{self.account}:oidc-provider/oidc.eks.{self.region}.amazonaws.com/id/{oidc_id}")
    cluster = eks.Cluster.from_cluster_attributes(
      self,
      "EksCluster",
      cluster_name=cluster_name,
      open_id_connect_provider=provider,
      kubectl_role_arn=f"arn:aws:iam::{self.account}:role/EksAdminRole-{cluster_name}"
    )

    EksNodegroupRole = iam.Role.from_role_name(
      self, 
      "ExistingNodegroupRole",
      role_name="EksNodegroupRole"
    )

    karpenter_inst_profile = iam.InstanceProfile(
      self,
      "KarpeneterInstanceProfile",
      instance_profile_name=f"KarpenterNodeInstanceProfile-{cluster_name}",
      role=EksNodegroupRole
    )

    KarpenterInterruptionQueue = sqs.Queue(self, "KarpenterInterruptionQueue",
      retention_period=duration.seconds(300),
      queue_name=f"{cluster_name}",
      encryption=sqs.QueueEncryption.SQS_MANAGED    
    )

    KarpenterInterruptionQueuePolicyDocument = iam.PolicyDocument(
      statements=[
        iam.PolicyStatement(
          effect=iam.Effect.ALLOW,
          actions=["sqs:SendMessage"],
          resources=[KarpenterInterruptionQueue.queue_arn],
          principals=[
            iam.ServicePrincipal("events.amazonaws.com"),
            iam.ServicePrincipal("sqs.amazonaws.com")
          ]
        )
      ]
    )

    KarpenterInterruptionQueuePolicy = sqs.CfnQueuePolicy(
      self, 
      "KarpenterInterruptionQueuePolicy",
      queues=[f"{KarpenterInterruptionQueue.queue_name}"],
      policy_document=KarpenterInterruptionQueuePolicyDocument
    )

    KarpenterSAPolicyStatementA = iam.PolicyStatement(
      actions=[
        'ec2:CreateLaunchTemplate',
        'ec2:DeleteLaunchTemplate',
        'ec2:CreateFleet',
        'ec2:RunInstances',
        'ec2:CreateTags',
        'ec2:TerminateInstances',
        'ec2:DescribeLaunchTemplates',
        'ec2:DescribeInstances',
        'ec2:DescribeSecurityGroups',
        'ec2:DescribeSubnets',
        'ec2:DescribeInstanceTypes',
        'ec2:DescribeInstanceTypeOfferings',
        'ec2:DescribeAvailabilityZones',
        'ssm:GetParameter',
        'pricing:GetProducts',
        'ec2:DescribeSpotPriceHistory',
        'ec2:DescribeImages'
      ],
      resources=['*'],
      effect=iam.Effect.ALLOW
    )

    KarpenterSAPolicyStatementB = iam.PolicyStatement(
      actions=['iam:PassRole'],
      resources=[EksNodegroupRole.role_arn],
      effect=iam.Effect.ALLOW
    )

    KarpenterSAPolicyStatementC = iam.PolicyStatement(
      actions=[
        'sqs:DeleteMessage',
        'sqs:GetQueueAttributes',
        'sqs:GetQueueUrl',
        'sqs:ReceiveMessage'
      ],
      resources=[KarpenterInterruptionQueue.queue_arn],
      effect=iam.Effect.ALLOW
    )

    conditions = CfnJson(self, "ConditionJson",
      value={
        f"oidc.eks.{self.region}.amazonaws.com/id/{oidc_id}:sub": "system:serviceaccount:karpenter:karpenter",
        f"oidc.eks.{self.region}.amazonaws.com/id/{oidc_id}:aud": "sts.amazonaws.com"
      }
    )

    KarpenterSARole_policy_document = iam.PolicyDocument(
      statements=[
        KarpenterSAPolicyStatementA,
        KarpenterSAPolicyStatementB,
        KarpenterSAPolicyStatementC
        # KarpenterSAPolicyStatementD
      ]
    )

    karpenter_sa = eks.ServiceAccount(
      self,
      "KarpenterSA",
      cluster=cluster,
      name="karpenter",
      namespace="karpenter",
      annotations={
        "eks.amazonaws.com/role-arn": f"arn:aws:iam::{self.account}:role/KarpenterSARole"
      }
    )

    KarpenterSARole = karpenter_sa.role
    iam.Policy(
      self,
      "KarpenterSARoleInlinePolicy",
      roles=[KarpenterSARole],
      document=KarpenterSARole_policy_document
    )

    target = targets.SqsQueue(
      queue=KarpenterInterruptionQueue
    )

    ScheduledChangeRule = events.Rule(
      self,
      "ScheduledChangeRule",
      event_pattern=events.EventPattern(
        source=["aws.health"],
        detail_type=["AWS Health Event"]
      )
    )
    ScheduledChangeRule.add_target(target)

    SpotInterruptionRule = events.Rule(
      self,
      "SpotInterruptionRule",
      event_pattern=events.EventPattern(
        source=["aws.ec2"],
        detail_type=["EC2 Spot Instance Interruption Warning"]
      )
    )
    SpotInterruptionRule.add_target(target)

    RebalanceRule = events.Rule(
      self,
      "RebalanceRule",
      event_pattern=events.EventPattern(
        source=["aws.ec2"],
        detail_type=["EC2 Instance Rebalance Recommendation"]
      )
    )
    RebalanceRule.add_target(target)

    InstanceStateChangeRule = events.Rule(
      self,
      "InstanceStateChangeRule",
      event_pattern=events.EventPattern(
        source=["aws.ec2"],
        detail_type=["EC2 Instance State-change Notification"]
      )
    )
    InstanceStateChangeRule.add_target(target)
    
    eks.HelmChart(self, "KarpenterChart",
      cluster=cluster,
      chart="karpenter",
      repository="oci://public.ecr.aws/karpenter/karpenter",
      namespace="karpenter",
      create_namespace=True,
      version="v0.30.0",
      values={
        "settings": {
          "aws": {
            "clusterName": f"{cluster_name}",
            "defaultInstanceProfile": f"KarpenterNodeInstanceProfile-{cluster_name}",
            "interruptionQueueName": f"{cluster_name}"
          }
        },
        "controller": {
          "resources": {
            "requests": {
              "cpu": "1",
              "memory": "1Gi"
            },
            "limits": {
              "cpu": "1",
              "memory": "1Gi"
            }
          }
        } 
      }
    )

```

**Expected Behavior**:

The helm chart should be created successfully and I should see karpeneter resources in my cluster.

**Reproduction Steps** (Please include YAML):

**Versions**:
- Kubernetes Version  v1.28.2: 

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ashishkurian** [comment]
Hi Folks,

After more reading I ran into this info: https://github.com/aws/aws-cdk/tree/main/packages/aws-cdk-lib/aws-eks#using-existing-clusters.

When I added the root principal to my eks master role, the SA and Helm charts are created successfully.

So I can close this issue.
