### ISSUE TITLE
Installing Karpenter with defaultProvisioner results in nil reference error.

### ISSUE THREAD

**Issue by Skarlso** [aws/karpenter#854]
## Version

**Karpenter**: v0.4.3

**Kubernetes**: v1.20.0

## Expected Behavior

Installing Karpenter with `eksctl` on a single node cluster adding all iam roles, services, and enabling installing defaultProvider should work.

## Actual Behavior

Got a nil reference error:

```
2021-11-25T19:31:20.668Z        INFO    controller.controller.Metrics   Starting workers        {"commit": "dc47849", "reconciler group": "karpenter.sh", "reconciler kind": "Provisioner", "worker count": 10}
E1125 19:31:20.669049       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 372 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x1dc5800, 0x37a1200})
        k8s.io/apimachinery@v0.20.7/pkg/util/runtime/runtime.go:74 +0x85
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x0})
        k8s.io/apimachinery@v0.20.7/pkg/util/runtime/runtime.go:48 +0x75
panic({0x1dc5800, 0x37a1200})
        runtime/panic.go:1038 +0x215
github.com/awslabs/karpenter/pkg/cloudprovider/aws/apis/v1alpha1.Deserialize(0xc0004b5498)
        github.com/awslabs/karpenter/pkg/cloudprovider/aws/apis/v1alpha1/provider.go:55 +0x96
github.com/awslabs/karpenter/pkg/cloudprovider/aws.(*CloudProvider).GetInstanceTypes(0xc000664fc0, {0x250b3d8, 0xc00039f260}, 0x0)
        github.com/awslabs/karpenter/pkg/cloudprovider/aws/cloudprovider.go:136 +0x2f
github.com/awslabs/karpenter/pkg/controllers/metrics.(*Controller).updateNodeCounts(0xc000a2b980, {0x250b3d8, 0xc00039f260}, 0xc0004b5380)
        github.com/awslabs/karpenter/pkg/controllers/metrics/controller.go:101 +0x65
github.com/awslabs/karpenter/pkg/controllers/metrics.(*Controller).updateCounts.func1(0x0)
        github.com/awslabs/karpenter/pkg/controllers/metrics/controller.go:94 +0x57
k8s.io/client-go/util/workqueue.ParallelizeUntil.func1()
        k8s.io/client-go@v0.20.7/util/workqueue/parallelizer.go:90 +0x150
created by k8s.io/client-go/util/workqueue.ParallelizeUntil
        k8s.io/client-go@v0.20.7/util/workqueue/parallelizer.go:76 +0x1dc
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x16d1f76]

goroutine 372 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x0})
        k8s.io/apimachinery@v0.20.7/pkg/util/runtime/runtime.go:55 +0xd8
panic({0x1dc5800, 0x37a1200})
        runtime/panic.go:1038 +0x215
github.com/awslabs/karpenter/pkg/cloudprovider/aws/apis/v1alpha1.Deserialize(0xc0004b5498)
        github.com/awslabs/karpenter/pkg/cloudprovider/aws/apis/v1alpha1/provider.go:55 +0x96
github.com/awslabs/karpenter/pkg/cloudprovider/aws.(*CloudProvider).GetInstanceTypes(0xc000664fc0, {0x250b3d8, 0xc00039f260}, 0x0)
        github.com/awslabs/karpenter/pkg/cloudprovider/aws/cloudprovider.go:136 +0x2f
github.com/awslabs/karpenter/pkg/controllers/metrics.(*Controller).updateNodeCounts(0xc000a2b980, {0x250b3d8, 0xc00039f260}, 0xc0004b5380)
        github.com/awslabs/karpenter/pkg/controllers/metrics/controller.go:101 +0x65
github.com/awslabs/karpenter/pkg/controllers/metrics.(*Controller).updateCounts.func1(0x0)
        github.com/awslabs/karpenter/pkg/controllers/metrics/controller.go:94 +0x57
k8s.io/client-go/util/workqueue.ParallelizeUntil.func1()
        k8s.io/client-go@v0.20.7/util/workqueue/parallelizer.go:90 +0x150
created by k8s.io/client-go/util/workqueue.ParallelizeUntil
        k8s.io/client-go@v0.20.7/util/workqueue/parallelizer.go:76 +0x1dc
```

## Steps to Reproduce the Problem

Helm install with defaultProvisioner set to `true.

**Comment by ellistarn** [comment]
Hey! I think this is a dup of https://github.com/aws/karpenter/issues/818. This is fixed in the next release, which I'm planning on cutting today.

**Comment by Skarlso** [comment]
Awesome! Nice :)

**Comment by ellistarn** [comment]
You should be able to work around it by recreating your provisioner once the webhook has come online.
